# Kustomize the deployment
#
# See
# * https://github.com/kubernetes-sigs/kustomize/tree/master/docs
bases:
# Note: only the resources listed in ../../base/kustomization.yaml can be kustomized
- ../../base

patchesJSON6902:
- target:
    version: v1
    kind: Service
    name: eclipse-hawkbit    
  path: patches/add_load_balancer_ip.yaml