apiVersion: v1
kind: Service
metadata:
  name: mail-notification-service
  namespace: extensions
  labels:
    app: mail-notification
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: mail-notification
