config:
  application:
    spring:
      security:
        user:
          name: admin
  secrets:
    spring:
      security:
        user:
          password: "{noop}<TODO>"
resources:
  requests:
    memory: 1024Mi
  limits:
    cpu: 500m
    memory: 1536Mi
